import jsPDF from 'jspdf';
import type { ExportData } from '../types';

export function exportToPdf(data: ExportData) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addPage = () => { doc.addPage(); y = margin; };
  const checkPage = (need: number) => { if (y + need > 280) addPage(); };

  // Header bar
  doc.setFillColor(168, 85, 247);
  doc.rect(0, 0, pageW, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Health Awareness Chatbot', margin, 12);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Consultation Report', margin, 19);
  y = 36;

  // Title & meta
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, margin, y);
  y += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Date: ${new Date(data.created_at).toLocaleString()}`, margin, y);
  y += 5;
  doc.text(`Messages: ${data.total_messages}`, margin, y);
  y += 5;
  doc.text(`Session ID: ${data.session_id}`, margin, y);
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  // Messages
  for (const msg of data.messages) {
    const isUser = msg.role === 'user';
    const label = isUser ? 'You' : 'Health Assistant';
    const voiceBadge = msg.message_type === 'voice' ? ' [Voice]' : '';
    const time = new Date(msg.created_at).toLocaleTimeString('en-US', {
      hour: '2-digit', minute: '2-digit',
    });

    // Label
    checkPage(20);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(isUser ? 168 : 80, isUser ? 85 : 80, isUser ? 247 : 80);
    doc.text(`${label}${voiceBadge}  —  ${time}`, margin, y);
    y += 5;

    // Content
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(msg.content, contentW);
    for (const line of lines) {
      checkPage(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 4;
  }

  // Footer
  checkPage(20);
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 6;
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.text(
    'Generated by Health Awareness Chatbot — For informational purposes only.',
    margin, y,
  );

  doc.save(`${data.title.replace(/\s+/g, '_')}_report.pdf`);
}
